### ISSUE TITLE
Data Set not accessible via LFS or Dropdown Link

### ISSUE THREAD

**Issue by shaunak09vb** [junaidiqbalsyed/Covid_detection_CNN#1]
The data set is not available via the dropdown link or via LFS. What is the walk around to fetch the data.

**Comment by junaidiqbalsyed** [comment]
I have uploaded the data on drop box. Why don't you use !wget command and download it. I have mentioned that in Readme file

**Comment by shaunak09vb** [comment]
I get a 404 Not Found Error. When I copy the dropbox link separately in the browser, it shows me "resource not found". Please check it once at your end.

**Comment by shaunak09vb** [comment]
Error Image Link: https://drive.google.com/file/d/1ADJMC7r8tcIudk1VecAFi4b32dEDiHe_/view?usp=sharing

**Comment by junaidiqbalsyed** [comment]
Oh let me look into it

**Comment by junaidiqbalsyed** [comment]
![Screenshot (175)](https://user-images.githubusercontent.com/49427723/121042863-b5601f80-c7d1-11eb-933a-18e4d189eb42.png)
its working just fine 

try with this : 
https://www.dropbox.com/s/e1r2laj50nh4tez/COVID-19_Radiography_Dataset.zip?dl=0

Let me know if it works

**Comment by shaunak09vb** [comment]
It works now. Thank You.
